/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_hospital;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author johnn
 */
public class EditarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form EditarUsuario
     */
    public EditarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonnombre = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        usuarioa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        contraa = new javax.swing.JPasswordField();
        bottonbuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        botonusuario = new javax.swing.JRadioButton();
        botoncontra = new javax.swing.JRadioButton();
        veri = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        valorAnterior = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nuevoValor = new javax.swing.JTextField();
        camiarcosos = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("   Editar Usuario   ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(botonnombre);
        botonnombre.setText("Nombre");
        botonnombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                botonnombreFocusGained(evt);
            }
        });
        botonnombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonnombreMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Que usuario desea editar");

        usuarioa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Contrasena del usuario");

        bottonbuscar.setText("Buscar Usuario");
        bottonbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottonbuscarMouseClicked(evt);
            }
        });
        bottonbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonbuscarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Que decea editar:");

        buttonGroup1.add(botonusuario);
        botonusuario.setText("Usuario");
        botonusuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                botonusuarioFocusGained(evt);
            }
        });
        botonusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonusuarioMouseClicked(evt);
            }
        });

        buttonGroup1.add(botoncontra);
        botoncontra.setText("Contrasena");
        botoncontra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                botoncontraFocusGained(evt);
            }
        });
        botoncontra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoncontraMouseClicked(evt);
            }
        });

        veri.setForeground(new java.awt.Color(255, 51, 0));
        veri.setText(" ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Valor Anterior:");

        valorAnterior.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valorAnterior.setText(" ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Nuevo Valor:");

        camiarcosos.setText("Cambiar Valor");
        camiarcosos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                camiarcososMouseClicked(evt);
            }
        });
        camiarcosos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camiarcososActionPerformed(evt);
            }
        });

        jButton3.setText("Volver Menu");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(camiarcosos)
                .addGap(136, 136, 136))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(usuarioa, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addComponent(jLabel1))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(contraa)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(bottonbuscar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(valorAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botonusuario)
                                            .addComponent(botonnombre)
                                            .addComponent(botoncontra)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(veri, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nuevoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, jLabel5, jLabel6});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usuarioa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(contraa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bottonbuscar)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonnombre)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(veri, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonusuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botoncontra)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(valorAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nuevoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(camiarcosos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton3))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {contraa, usuarioa});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, jLabel5, jLabel6});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {nuevoValor, valorAnterior});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//////////////////

    /*
    Botones buscar
     */
    //////////////
    private void bottonbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottonbuscarMouseClicked
        // TODO add your handling code here:

        logica log = new logica();
        buscar = log.BuscarUsuario(usuarioa.getText(), contraa.getText());
    }//GEN-LAST:event_bottonbuscarMouseClicked

    private void botonnombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonnombreMouseClicked

    }//GEN-LAST:event_botonnombreMouseClicked

    private void botonusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonusuarioMouseClicked

    }//GEN-LAST:event_botonusuarioMouseClicked

    private void botoncontraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoncontraMouseClicked

    }//GEN-LAST:event_botoncontraMouseClicked

    private void camiarcososActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camiarcososActionPerformed

    }//GEN-LAST:event_camiarcososActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        MenuUsuario mu = new MenuUsuario();
        mu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3MouseClicked
//////////////////

    /*
    Boton cambiar
     */
    //////////////
    private void camiarcososMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camiarcososMouseClicked
        // TODO add your handling code here
        logica log = new logica();
        JOptionPane.showMessageDialog(null, cambiar);
        if (buscar == false) {
            JOptionPane.showMessageDialog(null, "No as buscado la cuenta");
        } else if (buscar == true) {
            //cambiar la info
            switch (cambiar) {
                case 0:
                    JOptionPane.showMessageDialog(null, "No as elegido que cambiar");
                    break;
                case 1:
                    //cambio info
                    log.EditarUsuario(nuevoValor.getText(), usuarioa.getText(), contraa.getText(), 1);
                    JOptionPane.showMessageDialog(null, "Cambiado con exito");
                    JOptionPane.showMessageDialog(null, usuario, null, cambiar);
                    MenuPrincipal mp = new MenuPrincipal();
                    mp.setVisible(true);
                    dispose();
                    break;
                case 2:
                    //cambio info
                    log.EditarUsuario(nuevoValor.getText(), usuarioa.getText(), contraa.getText(), 2);
                    JOptionPane.showMessageDialog(null, "Cambiado con exito");
                    MenuPrincipal mpp = new MenuPrincipal();
                    mpp.setVisible(true);
                    dispose();
                    break;
                case 3:
                    //cambio info
                    log.EditarUsuario(nuevoValor.getText(), usuarioa.getText(), contraa.getText(), 3);
                    JOptionPane.showMessageDialog(null, "Cambiado con exito");
                    MenuPrincipal mppp = new MenuPrincipal();
                    mppp.setVisible(true);
                    dispose();
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_camiarcososMouseClicked

    private void bottonbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bottonbuscarActionPerformed
    //////////////////
    /*
    Botones gain
     */
    //////////////
    private void botonnombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_botonnombreFocusGained
        // TODO add your handling code here:
        logica log = new logica();
        if (buscar == false) {

        } else {

            cambiar = 3;
            try {
                valorAnterior.setText(log.getInfoUu(usuarioa.getText(), contraa.getText(), cambiar));
            } catch (IOException ex) {
                Logger.getLogger(EditarUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botonnombreFocusGained

    private void botonusuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_botonusuarioFocusGained
        // TODO add your handling code here:if(buscar==false){
        logica log = new logica();
        if (buscar == false) {

        } else {

            cambiar = 1;
            try {
                valorAnterior.setText(log.getInfoUu(usuarioa.getText(), contraa.getText(), cambiar));
            } catch (IOException ex) {
                Logger.getLogger(EditarUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botonusuarioFocusGained

    private void botoncontraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_botoncontraFocusGained
        // TODO add your handling code here:
        logica log = new logica();
        if (buscar == false) {

        } else {

            cambiar = 2;
            try {
                valorAnterior.setText(log.getInfoUu(usuarioa.getText(), contraa.getText(), cambiar));
            } catch (IOException ex) {
                Logger.getLogger(EditarUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botoncontraFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botoncontra;
    private javax.swing.JRadioButton botonnombre;
    private javax.swing.JRadioButton botonusuario;
    private javax.swing.JButton bottonbuscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton camiarcosos;
    private javax.swing.JPasswordField contraa;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nuevoValor;
    private javax.swing.JTextField usuarioa;
    private javax.swing.JLabel valorAnterior;
    private javax.swing.JLabel veri;
    // End of variables declaration//GEN-END:variables
    boolean buscar = false;
    int cambiar = 0;
    long usuario = 0;
}
